all: calc1 hijo1 calc2 calc3 calc4 hijo2

calc1: calc1.c
	gcc -o calc1 calc1.c

hijo1: hijo1.c
	gcc -o hijo1 hijo1.c

calc2: calc2.c
	gcc -o calc2 calc2.c

calc3: calc3.c
	gcc -o calc3 calc3.c

calc4: calc4.c
	gcc -o calc4 calc4.c

hijo2: hijo2.c
	gcc -o hijo2 hijo2.c

clean: 
	rm calc1 hijo1 calc2 calc3 calc4 hijo2