all: parser multiparser modifier

parser: parser.c
	gcc -o parser parser.c
	
multiparser: multiparser.c
	gcc -o multiparser multiparser.c
	
modifier: modifier.c
	gcc -o modifier modifier.c
	
clean:
	rm parser multiparser modifier MIPIPE
